SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE  FILM_GENRE;

TRUNCATE TABLE  FILM_LIKE;

TRUNCATE TABLE  USER_FRIEND;

TRUNCATE TABLE USERS RESTART IDENTITY;

TRUNCATE TABLE FILMS RESTART IDENTITY;

TRUNCATE TABLE GENRE RESTART IDENTITY;

TRUNCATE TABLE RATING RESTART IDENTITY;

SET REFERENTIAL_INTEGRITY TRUE;